version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - postgresql_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql_db:5432/sonarqube_database
      SONAR_JDBC_USERNAME: kurechii
      SONAR_JDBC_PASSWORD: 'Jt6(jJgcsY^[cv-'
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    ports:
      - "9002:9000"
  postgresql_db:
    image: postgres:latest
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: kurechii
      POSTGRES_PASSWORD: 'Jt6(jJgcsY^[cv-'
      POSTGRES_DB: sonarqube_database
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  postgresql_data:
