name: Create and Process XML File on PR

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  process-file:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Create XML File
      run: echo '<root><data>Unity test coverage stats</data></root>' > TestCoverage.xml

    - name: Read file contents
      id: read_file
      uses: andstor/file-reader-action@v1
      with:
        path: "TestCoverage.xml"

    - name: Process File
      run: |
        file_path="TestCoverage.xml"
        # Check if the file exists
        if [ -e "$file_path" ]; then
          echo "File $file_path exists"
          echo "::set-output name=boolVariable::true"
        else
          echo "File $file_path does not exist"
          echo "::set-output name=boolVariable::false"
        fi
      id: process-file

    - name: Comment on PR
      if: steps.process-file.outputs.boolVariable == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const readContent = `${{ steps.read_file.outputs.contents }}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: readContent
          })
