name: Process File and Comment on PR

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  process-file:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read and Process File
      run: |
        # Replace 'path/to/your/file.txt' with the actual path to your file
        file_content=$(cat "${{ github.workspace }}Message.txt")
        # Add your custom processing logic here
        processed_content="Processed content: $file_content"

    - name: Comment on PR
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const processedContent = context.inputs.processed_content;
          const context = github.context;
          github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: processedContent
          });